// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/queue.proto

package wo.mq.protobuf;

public final class QueueProtos {
  private QueueProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Queue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    wo.mq.protobuf.QueueProtos.QueueHeader getHeader();
    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated string content = 2;</code>
     */
    java.util.List<java.lang.String>
        getContentList();
    /**
     * <code>repeated string content = 2;</code>
     */
    int getContentCount();
    /**
     * <code>repeated string content = 2;</code>
     */
    java.lang.String getContent(int index);
    /**
     * <code>repeated string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.Queue}
   */
  public  static final class Queue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Queue)
      QueueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Queue.newBuilder() to construct.
    private Queue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Queue() {
      content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Queue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              wo.mq.protobuf.QueueProtos.QueueHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(wo.mq.protobuf.QueueProtos.QueueHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                content_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              content_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          content_ = content_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wo.mq.protobuf.QueueProtos.internal_static_protobuf_Queue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wo.mq.protobuf.QueueProtos.internal_static_protobuf_Queue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wo.mq.protobuf.QueueProtos.Queue.class, wo.mq.protobuf.QueueProtos.Queue.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private wo.mq.protobuf.QueueProtos.QueueHeader header_;
    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    public wo.mq.protobuf.QueueProtos.QueueHeader getHeader() {
      return header_ == null ? wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>optional .protobuf.QueueHeader header = 1;</code>
     */
    public wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance() : header_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList content_;
    /**
     * <code>repeated string content = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getContentList() {
      return content_;
    }
    /**
     * <code>repeated string content = 2;</code>
     */
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated string content = 2;</code>
     */
    public java.lang.String getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes(int index) {
      return content_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasHeader()) {
        if (!getHeader().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      for (int i = 0; i < content_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < content_.size(); i++) {
          dataSize += computeStringSizeNoTag(content_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getContentList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wo.mq.protobuf.QueueProtos.Queue)) {
        return super.equals(obj);
      }
      wo.mq.protobuf.QueueProtos.Queue other = (wo.mq.protobuf.QueueProtos.Queue) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.Queue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wo.mq.protobuf.QueueProtos.Queue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Queue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Queue)
        wo.mq.protobuf.QueueProtos.QueueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_Queue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_Queue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wo.mq.protobuf.QueueProtos.Queue.class, wo.mq.protobuf.QueueProtos.Queue.Builder.class);
      }

      // Construct using wo.mq.protobuf.QueueProtos.Queue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_Queue_descriptor;
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.Queue getDefaultInstanceForType() {
        return wo.mq.protobuf.QueueProtos.Queue.getDefaultInstance();
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.Queue build() {
        wo.mq.protobuf.QueueProtos.Queue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.Queue buildPartial() {
        wo.mq.protobuf.QueueProtos.Queue result = new wo.mq.protobuf.QueueProtos.Queue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (headerBuilder_ == null) {
            result.header_ = header_;
          } else {
            result.header_ = headerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          content_ = content_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wo.mq.protobuf.QueueProtos.Queue) {
          return mergeFrom((wo.mq.protobuf.QueueProtos.Queue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wo.mq.protobuf.QueueProtos.Queue other) {
        if (other == wo.mq.protobuf.QueueProtos.Queue.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (!other.content_.isEmpty()) {
          if (content_.isEmpty()) {
            content_ = other.content_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureContentIsMutable();
            content_.addAll(other.content_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasHeader()) {
          if (!getHeader().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wo.mq.protobuf.QueueProtos.Queue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wo.mq.protobuf.QueueProtos.Queue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private wo.mq.protobuf.QueueProtos.QueueHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          wo.mq.protobuf.QueueProtos.QueueHeader, wo.mq.protobuf.QueueProtos.QueueHeader.Builder, wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder> headerBuilder_;
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public wo.mq.protobuf.QueueProtos.QueueHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public Builder setHeader(wo.mq.protobuf.QueueProtos.QueueHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public Builder setHeader(
          wo.mq.protobuf.QueueProtos.QueueHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public Builder mergeHeader(wo.mq.protobuf.QueueProtos.QueueHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              header_ != null &&
              header_ != wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance()) {
            header_ =
              wo.mq.protobuf.QueueProtos.QueueHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public wo.mq.protobuf.QueueProtos.QueueHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      public wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>optional .protobuf.QueueHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          wo.mq.protobuf.QueueProtos.QueueHeader, wo.mq.protobuf.QueueProtos.QueueHeader.Builder, wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              wo.mq.protobuf.QueueProtos.QueueHeader, wo.mq.protobuf.QueueProtos.QueueHeader.Builder, wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.LazyStringList content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          content_ = new com.google.protobuf.LazyStringArrayList(content_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getContentList() {
        return content_.getUnmodifiableView();
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public int getContentCount() {
        return content_.size();
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public java.lang.String getContent(int index) {
        return content_.get(index);
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes(int index) {
        return content_.getByteString(index);
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public Builder setContent(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentIsMutable();
        content_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public Builder addContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentIsMutable();
        content_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public Builder addAllContent(
          java.lang.Iterable<java.lang.String> values) {
        ensureContentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, content_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public Builder clearContent() {
        content_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string content = 2;</code>
       */
      public Builder addContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentIsMutable();
        content_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Queue)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Queue)
    private static final wo.mq.protobuf.QueueProtos.Queue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wo.mq.protobuf.QueueProtos.Queue();
    }

    public static wo.mq.protobuf.QueueProtos.Queue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Queue>
        PARSER = new com.google.protobuf.AbstractParser<Queue>() {
      @java.lang.Override
      public Queue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Queue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Queue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Queue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wo.mq.protobuf.QueueProtos.Queue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueueHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.QueueHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string queueName = 1;</code>
     */
    boolean hasQueueName();
    /**
     * <code>required string queueName = 1;</code>
     */
    java.lang.String getQueueName();
    /**
     * <code>required string queueName = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueueNameBytes();

    /**
     * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
     */
    wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction getAction();

    /**
     * <code>optional string source = 3;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 3;</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();
  }
  /**
   * Protobuf type {@code protobuf.QueueHeader}
   */
  public  static final class QueueHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.QueueHeader)
      QueueHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueueHeader.newBuilder() to construct.
    private QueueHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueueHeader() {
      queueName_ = "";
      action_ = 1;
      source_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueueHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              queueName_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction value = wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              source_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wo.mq.protobuf.QueueProtos.internal_static_protobuf_QueueHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wo.mq.protobuf.QueueProtos.internal_static_protobuf_QueueHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wo.mq.protobuf.QueueProtos.QueueHeader.class, wo.mq.protobuf.QueueProtos.QueueHeader.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.QueueHeader.QueueAction}
     */
    public enum QueueAction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PUBLISH = 1;</code>
       */
      PUBLISH(1),
      /**
       * <code>SUBSCRIPT = 2;</code>
       */
      SUBSCRIPT(2),
      /**
       * <code>UNSUBSCRIPT = 3;</code>
       */
      UNSUBSCRIPT(3),
      /**
       * <code>PUT = 4;</code>
       */
      PUT(4),
      /**
       * <code>GET = 5;</code>
       */
      GET(5),
      ;

      /**
       * <code>PUBLISH = 1;</code>
       */
      public static final int PUBLISH_VALUE = 1;
      /**
       * <code>SUBSCRIPT = 2;</code>
       */
      public static final int SUBSCRIPT_VALUE = 2;
      /**
       * <code>UNSUBSCRIPT = 3;</code>
       */
      public static final int UNSUBSCRIPT_VALUE = 3;
      /**
       * <code>PUT = 4;</code>
       */
      public static final int PUT_VALUE = 4;
      /**
       * <code>GET = 5;</code>
       */
      public static final int GET_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QueueAction valueOf(int value) {
        return forNumber(value);
      }

      public static QueueAction forNumber(int value) {
        switch (value) {
          case 1: return PUBLISH;
          case 2: return SUBSCRIPT;
          case 3: return UNSUBSCRIPT;
          case 4: return PUT;
          case 5: return GET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<QueueAction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          QueueAction> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<QueueAction>() {
              public QueueAction findValueByNumber(int number) {
                return QueueAction.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return wo.mq.protobuf.QueueProtos.QueueHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final QueueAction[] VALUES = values();

      public static QueueAction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private QueueAction(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.QueueHeader.QueueAction)
    }

    private int bitField0_;
    public static final int QUEUENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object queueName_;
    /**
     * <code>required string queueName = 1;</code>
     */
    public boolean hasQueueName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string queueName = 1;</code>
     */
    public java.lang.String getQueueName() {
      java.lang.Object ref = queueName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          queueName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string queueName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueueNameBytes() {
      java.lang.Object ref = queueName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
     */
    public wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction getAction() {
      @SuppressWarnings("deprecation")
      wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction result = wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction.valueOf(action_);
      return result == null ? wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction.PUBLISH : result;
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object source_;
    /**
     * <code>optional string source = 3;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasQueueName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queueName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, source_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, queueName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, source_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wo.mq.protobuf.QueueProtos.QueueHeader)) {
        return super.equals(obj);
      }
      wo.mq.protobuf.QueueProtos.QueueHeader other = (wo.mq.protobuf.QueueProtos.QueueHeader) obj;

      if (hasQueueName() != other.hasQueueName()) return false;
      if (hasQueueName()) {
        if (!getQueueName()
            .equals(other.getQueueName())) return false;
      }
      if (hasAction() != other.hasAction()) return false;
      if (hasAction()) {
        if (action_ != other.action_) return false;
      }
      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQueueName()) {
        hash = (37 * hash) + QUEUENAME_FIELD_NUMBER;
        hash = (53 * hash) + getQueueName().hashCode();
      }
      if (hasAction()) {
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + action_;
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wo.mq.protobuf.QueueProtos.QueueHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wo.mq.protobuf.QueueProtos.QueueHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.QueueHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.QueueHeader)
        wo.mq.protobuf.QueueProtos.QueueHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_QueueHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_QueueHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wo.mq.protobuf.QueueProtos.QueueHeader.class, wo.mq.protobuf.QueueProtos.QueueHeader.Builder.class);
      }

      // Construct using wo.mq.protobuf.QueueProtos.QueueHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        queueName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wo.mq.protobuf.QueueProtos.internal_static_protobuf_QueueHeader_descriptor;
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.QueueHeader getDefaultInstanceForType() {
        return wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance();
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.QueueHeader build() {
        wo.mq.protobuf.QueueProtos.QueueHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wo.mq.protobuf.QueueProtos.QueueHeader buildPartial() {
        wo.mq.protobuf.QueueProtos.QueueHeader result = new wo.mq.protobuf.QueueProtos.QueueHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queueName_ = queueName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wo.mq.protobuf.QueueProtos.QueueHeader) {
          return mergeFrom((wo.mq.protobuf.QueueProtos.QueueHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wo.mq.protobuf.QueueProtos.QueueHeader other) {
        if (other == wo.mq.protobuf.QueueProtos.QueueHeader.getDefaultInstance()) return this;
        if (other.hasQueueName()) {
          bitField0_ |= 0x00000001;
          queueName_ = other.queueName_;
          onChanged();
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000004;
          source_ = other.source_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasQueueName()) {
          return false;
        }
        if (!hasAction()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wo.mq.protobuf.QueueProtos.QueueHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wo.mq.protobuf.QueueProtos.QueueHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object queueName_ = "";
      /**
       * <code>required string queueName = 1;</code>
       */
      public boolean hasQueueName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string queueName = 1;</code>
       */
      public java.lang.String getQueueName() {
        java.lang.Object ref = queueName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            queueName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string queueName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueueNameBytes() {
        java.lang.Object ref = queueName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queueName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string queueName = 1;</code>
       */
      public Builder setQueueName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        queueName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string queueName = 1;</code>
       */
      public Builder clearQueueName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        queueName_ = getDefaultInstance().getQueueName();
        onChanged();
        return this;
      }
      /**
       * <code>required string queueName = 1;</code>
       */
      public Builder setQueueNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        queueName_ = value;
        onChanged();
        return this;
      }

      private int action_ = 1;
      /**
       * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
       */
      public wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction getAction() {
        @SuppressWarnings("deprecation")
        wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction result = wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction.valueOf(action_);
        return result == null ? wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction.PUBLISH : result;
      }
      /**
       * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
       */
      public Builder setAction(wo.mq.protobuf.QueueProtos.QueueHeader.QueueAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.QueueHeader.QueueAction action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 3;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 3;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        source_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.QueueHeader)
    }

    // @@protoc_insertion_point(class_scope:protobuf.QueueHeader)
    private static final wo.mq.protobuf.QueueProtos.QueueHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wo.mq.protobuf.QueueProtos.QueueHeader();
    }

    public static wo.mq.protobuf.QueueProtos.QueueHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<QueueHeader>
        PARSER = new com.google.protobuf.AbstractParser<QueueHeader>() {
      @java.lang.Override
      public QueueHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueueHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueueHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueueHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wo.mq.protobuf.QueueProtos.QueueHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Queue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Queue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_QueueHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_QueueHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036resources/protobuf/queue.proto\022\010protob" +
      "uf\"?\n\005Queue\022%\n\006header\030\001 \001(\0132\025.protobuf.Q" +
      "ueueHeader\022\017\n\007content\030\002 \003(\t\"\261\001\n\013QueueHea" +
      "der\022\021\n\tqueueName\030\001 \002(\t\0221\n\006action\030\002 \002(\0162!" +
      ".protobuf.QueueHeader.QueueAction\022\016\n\006sou" +
      "rce\030\003 \001(\t\"L\n\013QueueAction\022\013\n\007PUBLISH\020\001\022\r\n" +
      "\tSUBSCRIPT\020\002\022\017\n\013UNSUBSCRIPT\020\003\022\007\n\003PUT\020\004\022\007" +
      "\n\003GET\020\005B\035\n\016wo.mq.protobufB\013QueueProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Queue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Queue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Queue_descriptor,
        new java.lang.String[] { "Header", "Content", });
    internal_static_protobuf_QueueHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_QueueHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_QueueHeader_descriptor,
        new java.lang.String[] { "QueueName", "Action", "Source", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
